spring.application.name=EduTrack

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/edutrack
spring.datasource.username=root
spring.datasource.password=Sh:12:06

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=dev
app.admin.email=admin@edutrack.local
app.admin.password=Admin@123

app.jwt.secret=VGhpcy1pcy1hLWRldi1vbmx5LWVkdXRyYWNrLXNlY3JldC1rZXktMjAyNg==
app.jwt.expiration=3600000